# Generated by Django 3.2.5 on 2021-08-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteins',
            name='links',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Links'),
        ),
    ]
