# Generated by Django 3.2.5 on 2021-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sequence', models.CharField(max_length=500, verbose_name='Sequence')),
                ('molecular_weight', models.FloatField(verbose_name='MolecularMolecularWeight')),
                ('length', models.IntegerField(verbose_name='Length')),
                ('charge', models.FloatField(verbose_name='Charge')),
                ('p_i', models.FloatField(verbose_name='pI')),
                ('a_index', models.FloatField(verbose_name='AIndex')),
                ('instaIndex', models.FloatField(verbose_name='InstaIndex')),
                ('BomanIndex', models.FloatField(verbose_name='BomanIndex')),
                ('hydrophobicity', models.FloatField(verbose_name='Hydrophobicity')),
                ('hmoment_angle', models.FloatField(verbose_name='MomentAngle')),
                ('hmoment_2', models.FloatField(verbose_name='Moment2')),
                ('pdb_id', models.CharField(max_length=256, verbose_name='PDBID')),
            ],
        ),
    ]
