# Generated by Django 3.2.5 on 2021-08-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampdb', '0002_alter_proteins_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteins',
            old_name='mol_weight_timy',
            new_name='mol_weight_tiny',
        ),
        migrations.AlterField(
            model_name='proteins',
            name='cytoplasmic',
            field=models.BooleanField(verbose_name='Cytoplasmic'),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='extracellular',
            field=models.BooleanField(verbose_name='Extracellular'),
        ),
    ]
