# Generated by Django 4.0.2 on 2024-07-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDBSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthetic_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Synthetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('s', models.CharField(max_length=500, verbose_name='Synthetic_sequence')),
                ('synthetic_Tiny', models.IntegerField(verbose_name='Tiny')),
                ('synthetic_Small', models.IntegerField(verbose_name='Small')),
                ('synthetic_Aliphtic', models.IntegerField(verbose_name='Synthetic_aliphatic')),
                ('synthetic_Aromatic', models.IntegerField(verbose_name='Synthetic_aromatic')),
                ('synthetic_non_polar', models.IntegerField(verbose_name='Synthetic_Non_Polar-aa')),
                ('synthetic_polar', models.IntegerField(verbose_name='Synthetic_Polar-aa')),
                ('synthetic_charged_aa', models.IntegerField(verbose_name='Synthetic_Charged-aa')),
                ('synthetic_basic', models.IntegerField(verbose_name='Synthetic_Basic-aa')),
                ('synthetic_acidic', models.CharField(max_length=255, verbose_name='Synthetic_Acidic-aa')),
                ('synthetic_mol_weight_tiny', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Tiny_aa')),
                ('synthetic_mol_weight_small', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Small_aa')),
                ('synthetic_mol_weight_apliphatic', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Aliphtic_aa')),
                ('synthetic_mol_weight_aromatic', models.CharField(max_length=255, verbose_name='Synthetic_Mole%-Aromatic_aa')),
                ('synthetic_mol_weight_non_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Non_Polar_aa')),
                ('synthetic_mol_weight_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Polar_aa')),
                ('synthetic_mol_weight_charged', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Charged_aa')),
                ('synthetic_mol_weight_basic', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Mole%-Basic_aa')),
                ('synthetic_mol_weight_acidic', models.IntegerField(default=None, verbose_name='Synthetic_Mole%-Acidic_aa')),
                ('synthetic_molecular_weight', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_mw')),
                ('synthetic_length', models.IntegerField(default=None, verbose_name='Synthetic_length')),
                ('synthetic_charge', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Charge')),
                ('synthetic_isolelectric_point', models.FloatField(max_length=255, verbose_name='Synthetic_Isolelectric point')),
                ('synthetic_aliphatic_Index', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Aliphatic Index')),
                ('synthetic_instability_Index', models.FloatField(max_length=255, verbose_name='Synthetic_Instability Index')),
                ('synthetic_bomanIndex', models.FloatField(max_length=255, verbose_name='Synthetic_BomanIndex')),
                ('synthetic_hydrophobicity', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobicity')),
                ('synthetic_hydrophobic_moment', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobic moment')),
                ('synthetic_toxicity', models.CharField(default=None, max_length=255, verbose_name='Synthetic_Toxicity')),
                ('synthetic_hemolytic_activity', models.FloatField(max_length=255, verbose_name='Synthetic_Hemolytic activity')),
                ('synthetic_score', models.IntegerField(default=None, verbose_name='Synthetic_Score')),
                ('mutaions', models.CharField(default=None, max_length=255, verbose_name='Mutations')),
                ('mutaion_count', models.IntegerField(default=None, verbose_name='Mutation_count')),
                ('synthetic_pdb_name', models.CharField(default=None, max_length=255, verbose_name='Synthetic_PDBName')),
            ],
        ),
    ]
