# Generated by Django 4.0.5 on 2023-06-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDBSDQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PDBSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthetic_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PDBSTQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stargetprotein_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sdock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_dock', models.CharField(max_length=1000, verbose_name='S_dock')),
                ('image1', models.CharField(max_length=1000, verbose_name='Image1')),
                ('image2', models.CharField(max_length=1000, verbose_name='Image2')),
                ('rmsf_min', models.CharField(max_length=1000, verbose_name='RSMF_min')),
                ('total_score_before_refinement', models.CharField(max_length=1000, verbose_name='Total_score_before_Refinement')),
                ('i_sc_before_refinement', models.CharField(max_length=1000, verbose_name='I_sc_before_Refinement')),
                ('bb_rmsd_before_refinement', models.CharField(max_length=1000, verbose_name='bb_RMSD_before_Refinement')),
                ('total_score_after_refinement', models.CharField(max_length=1000, verbose_name='Total_score_after_Refinement')),
                ('bb_rmsd_after_refinement', models.CharField(max_length=1000, verbose_name='bb_RMSD_after_Refinement')),
            ],
        ),
        migrations.CreateModel(
            name='Stargetproteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stargets', models.CharField(blank=True, default=None, max_length=1000, verbose_name='Stargets')),
            ],
        ),
        migrations.CreateModel(
            name='Synthetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('synthetic_Sequence', models.CharField(max_length=500, verbose_name='Synthetic_sequence')),
                ('synthetic_Tiny', models.IntegerField(verbose_name='Tiny')),
                ('synthetic_Small', models.IntegerField(verbose_name='Small')),
                ('synthetic_Aliphtic', models.IntegerField(verbose_name='Synthetic_aliphatic')),
                ('synthetic_Aromatic', models.IntegerField(verbose_name='Synthetic_aromatic')),
                ('synthetic_non_polar', models.IntegerField(verbose_name='Synthetic_Non_Polar-aa')),
                ('synthetic_polar', models.IntegerField(verbose_name='Synthetic_Polar-aa')),
                ('synthetic_charged_aa', models.IntegerField(verbose_name='Synthetic_Charged-aa')),
                ('synthetic_basic', models.IntegerField(verbose_name='Synthetic_Basic-aa')),
                ('synthetic_acidic', models.CharField(max_length=255, verbose_name='Synthetic_Acidic-aa')),
                ('synthetic_mol_weight_tiny', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Tiny_aa')),
                ('synthetic_mol_weight_small', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Small_aa')),
                ('synthetic_mol_weight_apliphatic', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Aliphtic_aa')),
                ('synthetic_mol_weight_aromatic', models.CharField(max_length=255, verbose_name='Synthetic_Mole%-Aromatic_aa')),
                ('synthetic_mol_weight_non_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Non_Polar_aa')),
                ('synthetic_mol_weight_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Polar_aa')),
                ('synthetic_mol_weight_charged', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Charged_aa')),
                ('synthetic_mol_weight_basic', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Mole%-Basic_aa')),
                ('synthetic_mol_weight_acidic', models.IntegerField(default=None, verbose_name='Synthetic_Mole%-Acidic_aa')),
                ('synthetic_molecular_weight', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_mw')),
                ('synthetic_length', models.IntegerField(default=None, verbose_name='Synthetic_length')),
                ('synthetic_charge', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Charge')),
                ('synthetic_isolelectric_point', models.FloatField(max_length=255, verbose_name='Synthetic_Isolelectric point')),
                ('synthetic_aliphatic_Index', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Aliphatic Index')),
                ('synthetic_instability_Index', models.FloatField(max_length=255, verbose_name='Synthetic_Instability Index')),
                ('synthetic_bomanIndex', models.FloatField(max_length=255, verbose_name='Synthetic_BomanIndex')),
                ('synthetic_hydrophobicity', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobicity')),
                ('synthetic_hydrophobic_moment', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobic moment')),
                ('synthetic_toxicity', models.CharField(default=None, max_length=255, verbose_name='Synthetic_Toxicity')),
                ('synthetic_hemolytic_activity', models.FloatField(max_length=255, verbose_name='Synthetic_Hemolytic activity')),
                ('synthetic_score', models.IntegerField(default=None, verbose_name='Synthetic_Score')),
                ('synthetic_pdb_name', models.CharField(default=None, max_length=255, verbose_name='Synthetic_PDBName')),
                ('sdock', models.ManyToManyField(related_name='sdock', to='synthetic.sdock')),
                ('starget_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthetic.stargetproteins')),
            ],
        ),
        migrations.AddField(
            model_name='sdock',
            name='stargets',
            field=models.ManyToManyField(to='synthetic.stargetproteins'),
        ),
    ]
