# Generated by Django 4.0.2 on 2023-11-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdock',
            name='stargets',
            field=models.ManyToManyField(to='synthetic.Stargetproteins'),
        ),
        migrations.AlterField(
            model_name='synthetic',
            name='sdock',
            field=models.ManyToManyField(related_name='sdock', to='synthetic.Sdock'),
        ),
    ]
