# Generated by Django 4.0.5 on 2023-06-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdbstquery',
            old_name='Stargetprotein_id',
            new_name='stargets_id',
        ),
    ]
