# Generated by Django 4.0.5 on 2023-06-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_1', models.CharField(max_length=1000, verbose_name='Dock')),
                ('image', models.CharField(max_length=1000, verbose_name='Image')),
                ('global_energy', models.CharField(max_length=1000, verbose_name='Global_Energy')),
                ('attr_vdw', models.CharField(max_length=1000, verbose_name='Attractive_VdW')),
                ('repl_vdw', models.CharField(max_length=1000, verbose_name='Repulsive_VdW')),
                ('binding_energy', models.CharField(max_length=1000, verbose_name='ACE')),
                ('hydrogen_bonding', models.CharField(max_length=1000, verbose_name='HB')),
            ],
        ),
        migrations.CreateModel(
            name='PDBDQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PDBQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PDBSDQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PDBSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synthetic_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PDBTQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sdock',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_dock', models.CharField(max_length=1000, verbose_name='S_dock')),
                ('image1', models.CharField(max_length=1000, verbose_name='Image1')),
                ('image2', models.CharField(max_length=1000, verbose_name='Image2')),
                ('rmsf_min', models.CharField(max_length=1000, verbose_name='RSMF_min')),
                ('total_score_before_refinement', models.CharField(max_length=1000, verbose_name='Total_score_before_Refinement')),
                ('i_sc_before_refinement', models.CharField(max_length=1000, verbose_name='I_sc_before_Refinement')),
                ('bb_rmsd_before_refinement', models.CharField(max_length=1000, verbose_name='bb_RMSD_before_Refinement')),
                ('total_score_after_refinement', models.CharField(max_length=1000, verbose_name='Total_score_after_Refinement')),
                ('bb_rmsd_after_refinement', models.CharField(max_length=1000, verbose_name='bb_RMSD_after_Refinement')),
            ],
        ),
        migrations.CreateModel(
            name='Synthetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('synthetic_Sequence', models.CharField(max_length=500, verbose_name='Synthetic_sequence')),
                ('synthetic_Tiny', models.IntegerField(verbose_name='Tiny')),
                ('synthetic_Small', models.IntegerField(verbose_name='Small')),
                ('synthetic_Aliphtic', models.IntegerField(verbose_name='Synthetic_aliphatic')),
                ('synthetic_Aromatic', models.IntegerField(verbose_name='Synthetic_aromatic')),
                ('synthetic_non_polar', models.IntegerField(verbose_name='Synthetic_Non_Polar-aa')),
                ('synthetic_polar', models.IntegerField(verbose_name='Synthetic_Polar-aa')),
                ('synthetic_charged_aa', models.IntegerField(verbose_name='Synthetic_Charged-aa')),
                ('synthetic_basic', models.IntegerField(verbose_name='Synthetic_Basic-aa')),
                ('synthetic_acidic', models.CharField(max_length=255, verbose_name='Synthetic_Acidic-aa')),
                ('synthetic_mol_weight_tiny', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Tiny_aa')),
                ('synthetic_mol_weight_small', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Small_aa')),
                ('synthetic_mol_weight_apliphatic', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Aliphtic_aa')),
                ('synthetic_mol_weight_aromatic', models.CharField(max_length=255, verbose_name='Synthetic_Mole%-Aromatic_aa')),
                ('synthetic_mol_weight_non_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Non_Polar_aa')),
                ('synthetic_mol_weight_polar', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Polar_aa')),
                ('synthetic_mol_weight_charged', models.FloatField(max_length=255, verbose_name='Synthetic_Mole%-Charged_aa')),
                ('synthetic_mol_weight_basic', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Mole%-Basic_aa')),
                ('synthetic_mol_weight_acidic', models.IntegerField(default=None, verbose_name='Synthetic_Mole%-Acidic_aa')),
                ('synthetic_molecular_weight', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_mw')),
                ('synthetic_length', models.IntegerField(default=None, verbose_name='Synthetic_length')),
                ('synthetic_charge', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Charge')),
                ('synthetic_isolelectric_point', models.FloatField(max_length=255, verbose_name='Synthetic_Isolelectric point')),
                ('synthetic_aliphatic_Index', models.FloatField(default=None, max_length=255, verbose_name='Synthetic_Aliphatic Index')),
                ('synthetic_instability_Index', models.FloatField(max_length=255, verbose_name='Synthetic_Instability Index')),
                ('synthetic_bomanIndex', models.FloatField(max_length=255, verbose_name='Synthetic_BomanIndex')),
                ('synthetic_hydrophobicity', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobicity')),
                ('synthetic_hydrophobic_moment', models.FloatField(max_length=255, verbose_name='Synthetic_Hydrophobic moment')),
                ('synthetic_toxicity', models.CharField(default=None, max_length=255, verbose_name='Synthetic_Toxicity')),
                ('synthetic_hemolytic_activity', models.FloatField(max_length=255, verbose_name='Synthetic_Hemolytic activity')),
                ('synthetic_score', models.IntegerField(default=None, verbose_name='Synthetic_Score')),
                ('synthetic_pdb_name', models.CharField(default=None, max_length=255, verbose_name='Synthetic_PDBName')),
            ],
        ),
        migrations.CreateModel(
            name='Targetproteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targets', models.CharField(max_length=1000, verbose_name='Targets')),
            ],
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amp', models.CharField(max_length=1000, verbose_name='AMP')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('sequence', models.CharField(max_length=1000, verbose_name='Sequence')),
                ('hemolytic_activity', models.FloatField(null=True, verbose_name='HemolyticActivity')),
                ('mic_value', models.FloatField(null=True, verbose_name='MICValue')),
                ('solubility', models.CharField(max_length=1000, verbose_name='Solubility')),
                ('tiny', models.IntegerField(null=True, verbose_name='Tiny')),
                ('small', models.IntegerField(null=True, verbose_name='Small')),
                ('aliphatic', models.IntegerField(null=True, verbose_name='Aliphatic')),
                ('aromatic', models.IntegerField(null=True, verbose_name='Aromatic')),
                ('non_polar', models.IntegerField(null=True, verbose_name='NonPolar')),
                ('polar', models.IntegerField(null=True, verbose_name='Polar')),
                ('charged_aa', models.IntegerField(null=True, verbose_name='ChargedAA')),
                ('basic', models.IntegerField(null=True, verbose_name='Basic')),
                ('acidic', models.FloatField(null=True, verbose_name='Acidic')),
                ('mol_weight_tiny', models.FloatField(null=True, verbose_name='MolWeightTiny')),
                ('mol_weight_small', models.FloatField(null=True, verbose_name='MolWeightSmall')),
                ('mol_weight_apliphatic', models.FloatField(null=True, verbose_name='MolWeightAliphatic')),
                ('mol_weight_aromatic', models.FloatField(null=True, verbose_name='MolWeightAromatic')),
                ('mol_weight_non_polar', models.FloatField(null=True, verbose_name='MolWeightNonPolar')),
                ('mol_weight_polar', models.FloatField(null=True, verbose_name='MolWeightPolar')),
                ('mol_weight_charged', models.FloatField(null=True, verbose_name='MolWeightCharged')),
                ('mol_weight_basic', models.FloatField(null=True, verbose_name='MolWeightBasic')),
                ('mol_weight_acidic', models.FloatField(null=True, verbose_name='MolWeightAcidic')),
                ('molecular_weight', models.FloatField(null=True, verbose_name='MolecularWeight')),
                ('length', models.IntegerField(null=True, verbose_name='Length')),
                ('charge', models.FloatField(null=True, verbose_name='Charge')),
                ('p_i', models.FloatField(null=True, verbose_name='pI')),
                ('a_index', models.FloatField(null=True, verbose_name='AIndex')),
                ('instaIndex', models.FloatField(null=True, verbose_name='InstaIndex')),
                ('BomanIndex', models.FloatField(null=True, verbose_name='BomanIndex')),
                ('hydrophobicity', models.FloatField(null=True, verbose_name='Hydrophobicity')),
                ('hmoment_angle', models.FloatField(null=True, verbose_name='HydrophobicMoment')),
                ('transmembrane', models.IntegerField(null=True, verbose_name='Transmembrane')),
                ('extracellular', models.BooleanField(null=True, verbose_name='Extracellular')),
                ('cytoplasmic', models.BooleanField(null=True, verbose_name='Cytoplasmic')),
                ('hydrophobic_plots', models.FloatField(null=True, verbose_name='HydrophobicPlots')),
                ('hydropathy_plots', models.FloatField(null=True, verbose_name='HydropathyPlots')),
                ('disulfide_end', models.CharField(max_length=1000, verbose_name='disulphides')),
                ('toxicity', models.CharField(max_length=1000, null=True, verbose_name='Toxicity')),
                ('rmsf', models.FloatField(null=True, verbose_name='RMSF')),
                ('flexibility', models.FloatField(null=True, verbose_name='Flexibility')),
                ('score', models.IntegerField(null=True, verbose_name='Score')),
                ('pdb_name', models.CharField(max_length=1000, verbose_name='PDBName')),
                ('dock', models.ManyToManyField(related_name='dock', to='abampdb.docks')),
                ('target_protein', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abampdb.targetproteins')),
            ],
        ),
        migrations.AddField(
            model_name='docks',
            name='targets',
            field=models.ManyToManyField(to='abampdb.targetproteins'),
        ),
    ]
