# Generated by Django 4.0.5 on 2023-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteins',
            name='target_proteins',
        ),
        migrations.AddField(
            model_name='proteins',
            name='dock',
            field=models.ManyToManyField(related_name='dock', to='abampdb.docks'),
        ),
    ]
