# Generated by Django 4.0.2 on 2022-10-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_1',
            field=models.CharField(max_length=256, verbose_name='dock_1'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_10',
            field=models.CharField(max_length=256, verbose_name='dock_10'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_11',
            field=models.CharField(max_length=256, verbose_name='dock_11'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_12',
            field=models.CharField(max_length=256, verbose_name='dock_12'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_13',
            field=models.CharField(max_length=256, verbose_name='dock_13'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_14',
            field=models.CharField(max_length=256, verbose_name='dock_14'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_15',
            field=models.CharField(max_length=256, verbose_name='dock_15'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_16',
            field=models.CharField(max_length=256, verbose_name='dock_16'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_17',
            field=models.CharField(max_length=256, verbose_name='dock_17'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_18',
            field=models.CharField(max_length=256, verbose_name='dock_18'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_19',
            field=models.CharField(max_length=256, verbose_name='dock_19'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_2',
            field=models.CharField(max_length=256, verbose_name='dock_2'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_20',
            field=models.CharField(max_length=256, verbose_name='dock_20'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_21',
            field=models.CharField(max_length=256, verbose_name='dock_21'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_22',
            field=models.CharField(max_length=256, verbose_name='dock_22'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_23',
            field=models.CharField(max_length=256, verbose_name='dock_23'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_24',
            field=models.CharField(max_length=256, verbose_name='dock_24'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_25',
            field=models.CharField(max_length=256, verbose_name='dock_25'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_26',
            field=models.CharField(max_length=256, verbose_name='dock_26'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_27',
            field=models.CharField(max_length=256, verbose_name='dock_27'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_28',
            field=models.CharField(max_length=256, verbose_name='dock_28'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_29',
            field=models.CharField(max_length=256, verbose_name='dock_29'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_3',
            field=models.CharField(max_length=256, verbose_name='dock_3'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_30',
            field=models.CharField(max_length=256, verbose_name='dock_30'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_4',
            field=models.CharField(max_length=256, verbose_name='dock_4'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_5',
            field=models.CharField(max_length=256, verbose_name='dock_5'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_6',
            field=models.CharField(max_length=256, verbose_name='dock_6'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_7',
            field=models.CharField(max_length=256, verbose_name='dock_7'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_8',
            field=models.CharField(max_length=256, verbose_name='dock_8'),
        ),
        migrations.AlterField(
            model_name='dock_proteins',
            name='dock_9',
            field=models.CharField(max_length=256, verbose_name='dock_9'),
        ),
    ]
