# Generated by Django 4.0.2 on 2023-12-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteins',
            name='transmembrane',
        ),
    ]
