# Generated by Django 4.0.5 on 2023-06-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDBSDQuery',
        ),
        migrations.DeleteModel(
            name='PDBSQuery',
        ),
        migrations.DeleteModel(
            name='PDBSTQuery',
        ),
        migrations.RemoveField(
            model_name='synthetic',
            name='sdock',
        ),
        migrations.RemoveField(
            model_name='synthetic',
            name='starget_protein',
        ),
        migrations.DeleteModel(
            name='Sdock',
        ),
        migrations.DeleteModel(
            name='Stargetproteins',
        ),
        migrations.DeleteModel(
            name='Synthetic',
        ),
    ]
