# Generated by Django 4.0.2 on 2023-12-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0002_remove_proteins_transmembrane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteins',
            name='disulfide_end',
        ),
        migrations.RemoveField(
            model_name='proteins',
            name='flexibility',
        ),
        migrations.RemoveField(
            model_name='proteins',
            name='hydropathy_plots',
        ),
        migrations.RemoveField(
            model_name='proteins',
            name='hydrophobic_plots',
        ),
    ]
