# Generated by Django 4.0.2 on 2023-06-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0002_remove_proteins_target_proteins_proteins_dock'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteins',
            name='target_protein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abampdb.targetproteins'),
        ),
        migrations.AlterField(
            model_name='docks',
            name='targets',
            field=models.ManyToManyField(to='abampdb.Targetproteins'),
        ),
        migrations.AlterField(
            model_name='proteins',
            name='dock',
            field=models.ManyToManyField(related_name='dock', to='abampdb.Docks'),
        ),
    ]
