# Generated by Django 4.0.2 on 2023-12-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abampdb', '0003_remove_proteins_disulfide_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteins',
            name='mic_value',
            field=models.CharField(max_length=1000, null=True, verbose_name='MICValue'),
        ),
    ]
